### ISSUE TITLE
Unexpected error when using download cbgs check point file for test

### ISSUE THREAD

**Issue by LiuWeijunAntihos** [poodarchu/Det3D#124]
Hi, there are some error occur when I try to use cbgs check point for test by

```
./tools/scripts/test.sh examples/cbgs/configs/nusc_all_vfev3_spmiddleresnetfhd_rpn2_mghead_syncbn.py test/ /mnt/truenas/scratch/weijun.liu/nusc/model_epoch_025_step_100100.pth
```

The error log is 

```
Traceback (most recent call last):
  File "./tools/dist_test.py", line 187, in <module>
    main()
  File "./tools/dist_test.py", line 106, in main
    checkpoint = load_checkpoint(model, args.checkpoint, map_location="cpu")
  File "/mnt/truenas/scratch/weijun.liu/workspace/Det3D/det3d/torchie/trainer/checkpoint.py", line 163, in load_checkpoint
    raise RuntimeError("No state_dict found in checkpoint file {}".format(filename))
RuntimeError: No state_dict found in checkpoint file /root/weijun.liu/nusc/model_epoch_025_step_100100.pth
Traceback (most recent call last):
Traceback (most recent call last):
  File "./tools/dist_test.py", line 187, in <module>
  File "./tools/dist_test.py", line 187, in <module>
    main()
  File "./tools/dist_test.py", line 106, in main
    main()
  File "./tools/dist_test.py", line 106, in main
    checkpoint = load_checkpoint(model, args.checkpoint, map_location="cpu")
  File "/mnt/truenas/scratch/weijun.liu/workspace/Det3D/det3d/torchie/trainer/checkpoint.py", line 163, in load_checkpoint
    checkpoint = load_checkpoint(model, args.checkpoint, map_location="cpu")
  File "/mnt/truenas/scratch/weijun.liu/workspace/Det3D/det3d/torchie/trainer/checkpoint.py", line 163, in load_checkpoint
    raise RuntimeError("No state_dict found in checkpoint file {}".format(filename))
RuntimeError: No state_dict found in checkpoint file /root/weijun.liu/nusc/model_epoch_025_step_100100.pth
    raise RuntimeError("No state_dict found in checkpoint file {}".format(filename))
RuntimeError: No state_dict found in checkpoint file /root/weijun.liu/nusc/model_epoch_025_step_100100.pth
Traceback (most recent call last):
  File "./tools/dist_test.py", line 187, in <module>
    main()
  File "./tools/dist_test.py", line 106, in main
    checkpoint = load_checkpoint(model, args.checkpoint, map_location="cpu")
  File "/mnt/truenas/scratch/weijun.liu/workspace/Det3D/det3d/torchie/trainer/checkpoint.py", line 163, in load_checkpoint
    raise RuntimeError("No state_dict found in checkpoint file {}".format(filename))
RuntimeError: No state_dict found in checkpoint file /root/weijun.liu/nusc/model_epoch_025_step_100100.pth
Traceback (most recent call last):
  File "./tools/dist_test.py", line 187, in <module>
    main()
  File "./tools/dist_test.py", line 106, in main
    checkpoint = load_checkpoint(model, args.checkpoint, map_location="cpu")
  File "/mnt/truenas/scratch/weijun.liu/workspace/Det3D/det3d/torchie/trainer/checkpoint.py", line 163, in load_checkpoint
    raise RuntimeError("No state_dict found in checkpoint file {}".format(filename))
RuntimeError: No state_dict found in checkpoint file /root/weijun.liu/nusc/model_epoch_025_step_100100.pth
2020-07-23 14:29:02,568 - INFO - Distributed testing: True
2020-07-23 14:29:02,568 - INFO - torch.backends.cudnn.benchmark: False
2020-07-23 14:29:02,659 - INFO - Finish RPN Initialization
2020-07-23 14:29:02,659 - INFO - num_classes: [1, 2, 2, 1, 2, 2], num_preds: [20, 40, 40, 20, 40, 40], num_dirs: []
2020-07-23 14:29:02,662 - INFO - Finish MultiGroupHead Initialization
Traceback (most recent call last):
  File "./tools/dist_test.py", line 187, in <module>
    main()
  File "./tools/dist_test.py", line 106, in main
    checkpoint = load_checkpoint(model, args.checkpoint, map_location="cpu")
  File "/mnt/truenas/scratch/weijun.liu/workspace/Det3D/det3d/torchie/trainer/checkpoint.py", line 163, in load_checkpoint
    raise RuntimeError("No state_dict found in checkpoint file {}".format(filename))
RuntimeError: No state_dict found in checkpoint file /root/weijun.liu/nusc/model_epoch_025_step_100100.pth
Traceback (most recent call last):
  File "./tools/dist_test.py", line 187, in <module>
    main()
  File "./tools/dist_test.py", line 106, in main
    checkpoint = load_checkpoint(model, args.checkpoint, map_location="cpu")
  File "/mnt/truenas/scratch/weijun.liu/workspace/Det3D/det3d/torchie/trainer/checkpoint.py", line 163, in load_checkpoint
    raise RuntimeError("No state_dict found in checkpoint file {}".format(filename))
RuntimeError: No state_dict found in checkpoint file /root/weijun.liu/nusc/model_epoch_025_step_100100.pth
Traceback (most recent call last):
  File "./tools/dist_test.py", line 187, in <module>
    main()
  File "./tools/dist_test.py", line 106, in main
    checkpoint = load_checkpoint(model, args.checkpoint, map_location="cpu")
  File "/mnt/truenas/scratch/weijun.liu/workspace/Det3D/det3d/torchie/trainer/checkpoint.py", line 163, in load_checkpoint
    raise RuntimeError("No state_dict found in checkpoint file {}".format(filename))
RuntimeError: No state_dict found in checkpoint file /root/weijun.liu/nusc/model_epoch_025_step_100100.pth
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', './tools/dist_test.py', '--local_rank=0', 'examples/cbgs/configs/nusc_all_vfev3_spmiddleresnetfhd_rpn2_mghead_syncbn.py', '--work_dir=test/', '--checkpoint=/root/weijun.liu/nusc/model_epoch_025_step_100100.pth']' returned non-zero exit status 1.

```

**Comment by tianweiy** [comment]
Please use [this](https://drive.google.com/drive/folders/1rhamAqegE9iOp18tzQVam4rOMhHjjnRM). Your checkpoint is the old one which is not supported in current version of Det3D
