### ISSUE TITLE
Circular dependency causes ImportError

### ISSUE THREAD

**Issue by jhultman** [poodarchu/Det3D#14]
Thanks so much for sharing your codebase. It really helps accelerate research.

I noticed there is a circular dependency between `det3d/core/__init__.py` and `det3d/datasets/kitti/kitti.py` (they import each other). 

To replicate: 
```
python -c 'import det3d.core'
>> 
  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/det3d/det3d/core/__init__.py", line 2, in <module>
    from .evaluation import *
  File "/root/det3d/det3d/core/evaluation/__init__.py", line 10, in <module>
    from .eval_hooks import KittiDistEvalmAPHook, KittiEvalmAPHookV2
  File "/root/det3d/det3d/core/evaluation/eval_hooks.py", line 8, in <module>
    from det3d import datasets, torchie
  File "/root/det3d/det3d/datasets/__init__.py", line 4, in <module>
    from .kitti import KittiDataset
  File "/root/det3d/det3d/datasets/kitti/__init__.py", line 1, in <module>
    from .kitti import KittiDataset
  File "/root/det3d/det3d/datasets/kitti/kitti.py", line 7, in <module>
    from det3d.core import box_np_ops
ImportError: cannot import name 'box_np_ops'
```

A workaround is to make sure to import `det3d.datasets` before importing `det3d.core`. A preferable solution would be to remove the circular dependency.

**Comment by poodarchu** [comment]
Can you create a merge request to solve this problem?

**Comment by qiushi223** [comment]
@jhultman I met the same problem. To solve this problem, I just removed "from .bbox import *" in the __init__.py. but then I had to change "from det3d.core import box_np_ops" to "from det3d.core.bbox import box_np_ops" in all .py files.  It can work now.
