### ISSUE TITLE
returned non-zero exit status 1.

### ISSUE THREAD

**Issue by shxzhao** [poodarchu/Det3D#150]
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-u', 'train.py', '--local_rank=0']' returned non-zero exit status 1.

How to solve this problem? Could you give me some tips? Thanks!

**Comment by poodarchu** [comment]
please provide the full error logs, not just the last line. 

Usually, the problem is not at the end of the log information.

**Comment by MengWangTHU** [comment]
perhaps i know the full error logs:
`CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_CUBLAS
    linked by target "spconv" in directory /home/l4/wm/spconv/src/spconv

-- Configuring incomplete, errors occurred!
See also "/home/l4/wm/spconv/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeOutput.log".
See also "/home/l4/wm/spconv/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 89, in <module>
    zip_safe=False,
  File "/home/l4/anaconda3/envs/sessd/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/l4/anaconda3/envs/sessd/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/l4/anaconda3/envs/sessd/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/l4/anaconda3/envs/sessd/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/l4/anaconda3/envs/sessd/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 299, in run
    self.run_command('build')
  File "/home/l4/anaconda3/envs/sessd/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/l4/anaconda3/envs/sessd/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/l4/anaconda3/envs/sessd/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/l4/anaconda3/envs/sessd/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/l4/anaconda3/envs/sessd/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 40, in run
    self.build_extension(ext)
  File "setup.py", line 72, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "/home/l4/anaconda3/envs/sessd/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/l4/wm/spconv', '-DCMAKE_PREFIX_PATH=/home/l4/anaconda3/envs/sessd/lib/python3.6/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.6', '-DSPCONV_BuildTests=OFF', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr"', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/l4/wm/spconv/build/lib.linux-x86_64-3.6/spconv', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.

I don't know how to solve the problem eithor. Thanks!!
`

**Comment by poodarchu** [comment]
Your cuda environment misses CUBLAS

**Comment by shxzhao** [comment]
Thank you for your reply! How to solve it? Do I need to reinstall the cuda?

**Comment by shxzhao** [comment]
running bdist_wheel
running build
running build_py
running build_ext
Release
|||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=/home/rtx-3090/anaconda3/envs/pytorch1/lib/python3.7/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.7', '-DSPCONV_BuildTests=OFF', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr"', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/rtx-3090/PycharmProjects/SE-SSD/spconv/build/lib.linux-x86_64-3.7/spconv', '-DCMAKE_BUILD_TYPE=Release']
-- The CXX compiler identification is GNU 7.5.0
-- The CUDA compiler identification is NVIDIA 11.1.74
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/local/cuda-11.1/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Caffe2: CUDA detected: 11.1
-- Caffe2: CUDA nvcc is: /usr/local/cuda-11.1/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda-11.1
-- Caffe2: Header version is: 11.1
-- Could NOT find CUDNN (missing: CUDNN_INCLUDE_PATH) 
CMake Warning at /home/rtx-3090/anaconda3/envs/pytorch1/lib/python3.7/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:109 (message):
  Caffe2: Cannot find cuDNN library.  Turning the option off
Call Stack (most recent call first):
  /home/rtx-3090/anaconda3/envs/pytorch1/lib/python3.7/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
  /home/rtx-3090/anaconda3/envs/pytorch1/lib/python3.7/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
  CMakeLists.txt:23 (find_package)


CMake Warning at /home/rtx-3090/anaconda3/envs/pytorch1/lib/python3.7/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:198 (message):
  Failed to compute shorthash for libnvrtc.so
Call Stack (most recent call first):
  /home/rtx-3090/anaconda3/envs/pytorch1/lib/python3.7/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
  /home/rtx-3090/anaconda3/envs/pytorch1/lib/python3.7/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
  CMakeLists.txt:23 (find_package)


-- Autodetected CUDA architecture(s):  8.6
-- Added CUDA NVCC flags for: -gencode;arch=compute_86,code=sm_86
CMake Error at /home/rtx-3090/anaconda3/envs/pytorch1/lib/python3.7/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:96 (message):
  Your installed Caffe2 version uses cuDNN but I cannot find the cuDNN
  libraries.  Please set the proper cuDNN prefixes and / or install cuDNN.
Call Stack (most recent call first):
  /home/rtx-3090/anaconda3/envs/pytorch1/lib/python3.7/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
  CMakeLists.txt:23 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/rtx-3090/PycharmProjects/SE-SSD/spconv/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeOutput.log".
See also "/home/rtx-3090/PycharmProjects/SE-SSD/spconv/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 89, in <module>
    zip_safe=False,
  File "/home/rtx-3090/anaconda3/envs/pytorch1/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/rtx-3090/anaconda3/envs/pytorch1/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/rtx-3090/anaconda3/envs/pytorch1/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/rtx-3090/anaconda3/envs/pytorch1/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/rtx-3090/anaconda3/envs/pytorch1/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 299, in run
    self.run_command('build')
  File "/home/rtx-3090/anaconda3/envs/pytorch1/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/rtx-3090/anaconda3/envs/pytorch1/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/rtx-3090/anaconda3/envs/pytorch1/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/rtx-3090/anaconda3/envs/pytorch1/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/rtx-3090/anaconda3/envs/pytorch1/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 40, in run
    self.build_extension(ext)
  File "setup.py", line 72, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "/home/rtx-3090/anaconda3/envs/pytorch1/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/rtx-3090/PycharmProjects/SE-SSD/spconv', '-DCMAKE_PREFIX_PATH=/home/rtx-3090/anaconda3/envs/pytorch1/lib/python3.7/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.7', '-DSPCONV_BuildTests=OFF', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr"', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/rtx-3090/PycharmProjects/SE-SSD/spconv/build/lib.linux-x86_64-3.7/spconv', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.


It shows that can't find the cudnn, but I have install it, how to solve it?  I install the cublas by pip install nvidia-cublas.

**Comment by shxzhao** [comment]
I solved it in https://github.com/traveller59/spconv/issues/277#issue-787551259. Thanks! @poodarchu @MengWangTHU
