### ISSUE TITLE
ImportError: cannot import name 'syncbn_gpu'

### ISSUE THREAD

**Issue by 451578928** [poodarchu/Det3D#20]
cxt@ubuntu4-X299X-AORUS-MASTER:~/codetest/det3d$ python tools/create_data.py kitti_data_prep --root_path=/home/cxt/Kitti/object/
/home/cxt/anaconda3/envs/second/lib/python3.6/site-packages/numba/cuda/envvars.py:17: NumbaWarning: 
Environment variables with the 'NUMBAPRO' prefix are deprecated and consequently ignored, found use of NUMBAPRO_NVVM=/usr/local/cuda/nvvm/lib64/libnvvm.so.

For more information about alternatives visit: ('http://numba.pydata.org/numba-doc/latest/cuda/overview.html', '#cudatoolkit-lookup')
  warnings.warn(errors.NumbaWarning(msg))
/home/cxt/anaconda3/envs/second/lib/python3.6/site-packages/numba/cuda/envvars.py:17: NumbaWarning: 
Environment variables with the 'NUMBAPRO' prefix are deprecated and consequently ignored, found use of NUMBAPRO_LIBDEVICE=/usr/local/cuda/nvvm/libdevice.

For more information about alternatives visit: ('http://numba.pydata.org/numba-doc/latest/cuda/overview.html', '#cudatoolkit-lookup')
  warnings.warn(errors.NumbaWarning(msg))
/home/cxt/anaconda3/envs/second/lib/python3.6/site-packages/numba/cuda/envvars.py:17: NumbaWarning: 
Environment variables with the 'NUMBAPRO' prefix are deprecated and consequently ignored, found use of NUMBAPRO_CUDA_DRIVER=/usr/lib/x86_64-linux-gnu/libcuda.so.

For more information about alternatives visit: ('http://numba.pydata.org/numba-doc/latest/cuda/overview.html', '#cudatoolkit-lookup')
  warnings.warn(errors.NumbaWarning(msg))
Traceback (most recent call last):
  File "tools/create_data.py", line 7, in <module>
    from det3d.datasets.kitti import kitti_common as kitti_ds
  File "/home/cxt/codetest/det3d/det3d/datasets/__init__.py", line 4, in <module>
    from .kitti import KittiDataset
  File "/home/cxt/codetest/det3d/det3d/datasets/kitti/__init__.py", line 1, in <module>
    from .kitti import KittiDataset
  File "/home/cxt/codetest/det3d/det3d/datasets/kitti/kitti.py", line 8, in <module>
    from det3d.datasets.custom import PointCloudDataset
  File "/home/cxt/codetest/det3d/det3d/datasets/custom.py", line 8, in <module>
    from .pipelines import Compose
  File "/home/cxt/codetest/det3d/det3d/datasets/pipelines/__init__.py", line 18, in <module>
    from .preprocess import Preprocess, Voxelization, AssignTarget
  File "/home/cxt/codetest/det3d/det3d/datasets/pipelines/preprocess.py", line 8, in <module>
    from det3d.builder import (
  File "/home/cxt/codetest/det3d/det3d/builder.py", line 18, in <module>
    from det3d.models.losses import GHMCLoss, GHMRLoss, losses
  File "/home/cxt/codetest/det3d/det3d/models/__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/home/cxt/codetest/det3d/det3d/models/backbones/__init__.py", line 1, in <module>
    from .scn import RCNNSpMiddleFHD, SpMiddleFHD
  File "/home/cxt/codetest/det3d/det3d/models/backbones/scn.py", line 6, in <module>
    from det3d.models.utils import Empty, change_default_args
  File "/home/cxt/codetest/det3d/det3d/models/utils/__init__.py", line 1, in <module>
    from .conv_module import ConvModule, build_conv_layer
  File "/home/cxt/codetest/det3d/det3d/models/utils/conv_module.py", line 7, in <module>
    from .norm import build_norm_layer
  File "/home/cxt/codetest/det3d/det3d/models/utils/norm.py", line 4, in <module>
    from det3d.ops.syncbn import DistributedSyncBN
  File "/home/cxt/codetest/det3d/det3d/ops/syncbn/__init__.py", line 1, in <module>
    from .syncbn import DistributedSyncBN
  File "/home/cxt/codetest/det3d/det3d/ops/syncbn/syncbn.py", line 12, in <module>
    from . import syncbn_gpu
ImportError: cannot import name 'syncbn_gpu'

**Comment by poodarchu** [comment]
have you compile the syncbn_gpu memory?

**Comment by 451578928** [comment]
Yes i ignored it now it's resolved

**Comment by 451578928** [comment]
But I encountered the same problem as on Second. I used TATIN V and the batch size was set to 4 (even set to 1)and it still didn't work. prompt:RuntimeError: CUDA out of memory.
