### ISSUE TITLE
No module named 'det3d.torchie.cnn.alexnet', resnet and vgg

### ISSUE THREAD

**Issue by hz3014** [poodarchu/Det3D#62]
First of all, thank you for your work!

When I was create dataset, the following error occurs:

 python tools/create_data.py nuscenes_data_prep --root_path=/media/hz3014/DataLinux/v1.0-trainval_blobs  --version="v1.0-trainval" --nsweeps=10
Traceback (most recent call last):
  File "tools/create_data.py", line 7, in <module>
    from det3d.datasets.kitti import kitti_common as kitti_ds
  File "/home/hz3014/Det3D/det3d/datasets/__init__.py", line 1, in <module>
    from .builder import build_dataset
  File "/home/hz3014/Det3D/det3d/datasets/builder.py", line 3, in <module>
    from det3d.utils import build_from_cfg
  File "/home/hz3014/Det3D/det3d/utils/__init__.py", line 2, in <module>
    from .registry import Registry, build_from_cfg
  File "/home/hz3014/Det3D/det3d/utils/registry.py", line 3, in <module>
    from det3d import torchie
  File "/home/hz3014/Det3D/det3d/torchie/__init__.py", line 2, in <module>
    from .cnn import *
  File "/home/hz3014/Det3D/det3d/torchie/cnn/__init__.py", line 1, in <module>
    from .alexnet import AlexNet
ModuleNotFoundError: No module named 'det3d.torchie.cnn.alexnet'

It seems like in det3d/torchie/cnn, there is no related module provided.

**Comment by poodarchu** [comment]
just detele it
