### ISSUE TITLE
Error in Nuscenes data preprocess 

### ISSUE THREAD

**Issue by chanyn** [poodarchu/Det3D#85]
When I run pointpillars or cbgs on nuscenes, I met following mistakes:
It happens at data preprocess, seems no point be sampled. If anyone meet this error before??

Original Traceback (most recent call last):
  File "/home/xuhang/anaconda3/envs/pointpillars/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/xuhang/anaconda3/envs/pointpillars/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/xuhang/anaconda3/envs/pointpillars/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/xuhang/green_zone_code/Det3D-master/det3d/datasets/nuscenes/nuscenes.py", line 177, in __getitem__
    return self.get_sensor_data(idx)
  File "/home/xuhang/green_zone_code/Det3D-master/det3d/datasets/nuscenes/nuscenes.py", line 172, in get_sensor_data
    data, _ = self.pipeline(res, info)
  File "/home/xuhang/green_zone_code/Det3D-master/det3d/datasets/pipelines/compose.py", line 23, in __call__
    res, info = t(res, info)
  File "/home/xuhang/green_zone_code/Det3D-master/det3d/datasets/pipelines/preprocess.py", line 160, in __call__
    calib=calib,
  File "/home/xuhang/green_zone_code/Det3D-master/det3d/core/sampler/sample_ops.py", line 220, in sample_all
    "points": np.concatenate(s_points_list, axis=0),
ValueError: need at least one array to concatenate

**Comment by poodarchu** [comment]
please insert a breakpoint to see what's going wrong at line 220.

**Comment by XiaomuWang** [comment]
Is it resolved? I also have this problem.

**Comment by ConanCui** [comment]
same problem, any solution?

**Comment by Linkon87** [comment]
Has anyone solved it? I had the same problem
