### ISSUE TITLE
spconv/indice.cu 60 cuda execution failed with error 98

### ISSUE THREAD

**Issue by chowkamlee81** [poodarchu/Det3D#88]
I installed spconv module succesfully. I had ubuntu18.0.4, cuda10.2 , torch=1.20 torch vision=0.4.0,

After installing, i tried execute python test/test_conv.py , but i got error below.. Kindly help

/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py:3335: RuntimeWarning: Mean of empty slice.
out=out, **kwargs)
/usr/local/lib/python3.6/dist-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
ret = ret.dtype.type(ret / rcount)
spconv time nan
Traceback (most recent call last):
File "test_conv.py", line 619, in
main()
File "test_conv.py", line 612, in main
out = net(features_t, indices_t, bs)
File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in call
result = self.forward(*input, **kwargs)
File "test_conv.py", line 57, in forward
return self.net(x)# .dense()
File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in call
result = self.forward(*input, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/spconv/modules.py", line 130, in forward
input = module(input)
File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in call
result = self.forward(*input, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/spconv/conv.py", line 177, in forward
use_hash=self.use_hash)
File "/usr/local/lib/python3.6/dist-packages/spconv/ops.py", line 93, in get_indice_pairs
stride, padding, dilation, out_padding, int(subm), int(transpose), int(use_hash))
RuntimeError: /module/src/lidar_detection/spconv-master/src/spconv/indice.cu 60
cuda execution failed with error 98

**Comment by poodarchu** [comment]
Did you install spconv using the version in my README.md?

**Comment by AlphaPlusTT** [comment]
@poodarchu i meet the similar problem and i indeed install the spconv using the version in your README.md

**Comment by AlphaPlusTT** [comment]
Traceback (most recent call last):
  File "./tools/train.py", line 133, in <module>
    main()
  File "./tools/train.py", line 128, in main
    logger=logger,
  File "/home/chi_zhang/yz/Det3D/det3d/torchie/apis/train.py", line 343, in train_detector
    trainer.run(data_loaders, cfg.workflow, cfg.total_epochs, local_rank=cfg.local_rank)
  File "/home/chi_zhang/yz/Det3D/det3d/torchie/trainer/trainer.py", line 536, in run
    epoch_runner(data_loaders[i], self.epoch, **kwargs)
  File "/home/chi_zhang/yz/Det3D/det3d/torchie/trainer/trainer.py", line 403, in train
    self.model, data_batch, train_mode=True, **kwargs
  File "/home/chi_zhang/yz/Det3D/det3d/torchie/trainer/trainer.py", line 362, in batch_processor_inline
    losses = model(example, return_loss=True)
  File "/home/chi_zhang/anaconda3/envs/det3d/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chi_zhang/anaconda3/envs/det3d/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 376, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/chi_zhang/anaconda3/envs/det3d/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chi_zhang/yz/Det3D/det3d/models/detectors/voxelnet.py", line 46, in forward
    x = self.extract_feat(data)
  File "/home/chi_zhang/yz/Det3D/det3d/models/detectors/voxelnet.py", line 24, in extract_feat
    input_features, data["coors"], data["batch_size"], data["input_shape"]
  File "/home/chi_zhang/anaconda3/envs/det3d/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chi_zhang/yz/Det3D/det3d/models/backbones/scn.py", line 191, in forward
    ret = self.middle_conv(ret)
  File "/home/chi_zhang/anaconda3/envs/det3d/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chi_zhang/anaconda3/envs/det3d/lib/python3.6/site-packages/spconv/modules.py", line 123, in forward
    input = module(input)
  File "/home/chi_zhang/anaconda3/envs/det3d/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chi_zhang/anaconda3/envs/det3d/lib/python3.6/site-packages/spconv/conv.py", line 155, in forward
    self.stride, self.padding, self.dilation, self.output_padding, self.subm, self.transposed, grid=input.grid)
  File "/home/chi_zhang/anaconda3/envs/det3d/lib/python3.6/site-packages/spconv/ops.py", line 89, in get_indice_pairs
    stride, padding, dilation, out_padding, int(subm), int(transpose))
RuntimeError: /home/chi_zhang/local/spconv/src/spconv/indice.cu 125
cuda execution failed with error 2
